// <auto-generated />
using System;
using Helpdesk.Modules.Organisation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Helpdesk.Modules.Organisation.Persistence.Migrations
{
    [DbContext(typeof(OrganisationDbContext))]
    partial class OrganisationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organisation")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Helpdesk.Modules.Organisation.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("departments", "organisation", t =>
                        {
                            t.HasCheckConstraint("ck_departments_key_format", "key ~ '^[A-Z][A-Z0-9]{1,9}$'");

                            t.HasCheckConstraint("ck_departments_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("Helpdesk.Modules.Organisation.Domain.DepartmentMembership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "DepartmentId");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_department_memberships_department_id");

                    b.ToTable("department_memberships", "organisation", t =>
                        {
                            t.HasCheckConstraint("ck_department_memberships_role", "role IN ('DepartmentAdmin','TeamLead','Agent','Viewer')");
                        });
                });

            modelBuilder.Entity("Helpdesk.Modules.Organisation.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "DepartmentId")
                        .HasName("ux_teams_id_department");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_teams_department_id");

                    b.ToTable("teams", "organisation", t =>
                        {
                            t.HasCheckConstraint("ck_teams_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("Helpdesk.Modules.Organisation.Domain.TeamMembership", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_team_memberships_user_id");

                    b.HasIndex("TeamId", "DepartmentId");

                    b.HasIndex("UserId", "DepartmentId");

                    b.ToTable("team_memberships", "organisation");
                });

            modelBuilder.Entity("Helpdesk.Modules.Organisation.Domain.DepartmentMembership", b =>
                {
                    b.HasOne("Helpdesk.Modules.Organisation.Domain.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Helpdesk.Modules.Organisation.Domain.Team", b =>
                {
                    b.HasOne("Helpdesk.Modules.Organisation.Domain.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Helpdesk.Modules.Organisation.Domain.TeamMembership", b =>
                {
                    b.HasOne("Helpdesk.Modules.Organisation.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "DepartmentId")
                        .HasPrincipalKey("Id", "DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_memberships_team_department");

                    b.HasOne("Helpdesk.Modules.Organisation.Domain.DepartmentMembership", null)
                        .WithMany()
                        .HasForeignKey("UserId", "DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_memberships_department_membership");
                });
#pragma warning restore 612, 618
        }
    }
}
